# Generated by Django 5.0.4 on 2024-05-21 02:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_task_completed_alter_task_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='prioryty',
            new_name='priority',
        ),
    ]
